[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
    "probe-rs",
    "run",
    "--chip",
    "nRF52833_xxAA",
    "--log-format",
    "{t} {L} {s}",
]

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

# tip: run `cargo clean` after changing these values
[env]
# default = "error". other options: trace、debug、warn、off
# to set by module: "warn,{crate}::{mod}=trace"
DEFMT_LOG = "debug"
DEFMT_RTT_BUFFER_SIZE = "1024"
